twin-te/twin-te

infra/staging/app/cronjob/Dockerfile, infra/staging/app/cronjob/update-course.sh, infra/staging/app/docker-compose.yml, infra/staging/app/proxy/Caddyfile, infra/staging/app/scripts/deploy-back.sh, infra/staging/db/docker-compose.yml, infra/staging/db/migration/Dockerfile, infra/staging/db/migration/migration.sh, infra/staging/db/scripts/deploy-back.sh
copy from [here](https://github.com/twin-te/twinte-infra-v4/tree/840a9beb1ee0c4f9232182fe29d3f0e6d1ce6a9d/staging).
=> [infra] copy staging from twinte-infra-v4

back/.air.toml
=> Fix building error of Go

sponsorship/Dockerfile, sponsorship/next.config.js
This reverts commit 5de7cd9d728fc73263c8b002fd77cb06dbc1c47d.
=> Revert "[sponsorship] デプロイ用のコンテナを修正 (#157)"

data-migration-v3-to-v4/import.sh
V3 → V4 でマイグレーション（データ移行）処理をするスクリプトを書きました。
一旦は動作確認のためローカル開発環境で動かすことを想定しています。
=> Add V3 -> V4 migration scripts

back/module/shared/domain/academic_year.go, back/module/shared/domain/idtype/already_read_id_gen.go, back/module/shared/domain/idtype/announcement_id_gen.go, back/module/shared/domain/idtype/checkout_session_id_gen.go, back/module/shared/domain/idtype/course_id_gen.go, back/module/shared/domain/idtype/event_id_gen.go, back/module/shared/domain/idtype/module_detail_id_gen.go, back/module/shared/domain/idtype/payment_history_id_gen.go, back/module/shared/domain/idtype/payment_user_id_gen.go, back/module/shared/domain/idtype/registered_course_id_gen.go, back/module/shared/domain/idtype/session_id_gen.go, back/module/shared/domain/idtype/subscription_id_gen.go, back/module/shared/domain/idtype/subscription_plan_id_gen.go, back/module/shared/domain/idtype/tag_id_gen.go, back/module/shared/domain/idtype/user_id_gen.go, back/module/shared/domain/non_negative_int.go, back/module/shared/domain/required_string.go, codegen/idtype/string_template.txt, codegen/idtype/uuid_template.txt
* Revert "[back] shared domain sql (#219)"
This reverts commit d7535203c2d20deed49c4ee7f815819fe874e62a.
* revert "[root] idtype sql (#218)"
This reverts commit 41f89f5dcd5a2198c997bb761727bd71bd33fd95.
=> [root] revert sql

back/module/timetable/adapter/query/registered_course.go, back/module/timetable/adapter/repository/registered_course.go, back/module/timetable/adapter/repository/registered_course_tag_id.go, back/module/timetable/dbmodel/registered_course.go, data-migration-v3-to-v4/main.py, data-migration-v3-to-v4/script/migrate.sh, db/migrations/000002_create_tables.down.sql, db/migrations/000002_create_tables.up.sql
This reverts commit 6ee5969e08afa8bd4c6e5639627edc6a481b6919.
=> Revert "[root] fix registered course tag ids (#222)"

back/module/timetable/adapter/query/registered_course.go, back/module/timetable/adapter/repository/registered_course.go, back/module/timetable/adapter/repository/registered_course_tag_id.go, back/module/timetable/dbmodel/registered_course.go, data-migration-v3-to-v4/main.py, data-migration-v3-to-v4/script/migrate.sh, db/migrations/000002_create_tables.down.sql, db/migrations/000002_create_tables.up.sql
This reverts commit 042d4a9921b67f37d8148233c96ab139968abe6a.
=> Revert "Revert "[root] fix registered course tag ids (#222)" (#225)"

data-migration-v3-to-v4/import.sh, data-migration-v3-to-v4/main.py
=> V3 -> V4 のデータ移行スクリプトを追加

front/src/usecases/announcement.ts, front/src/usecases/auth.ts, front/src/usecases/timetable.ts
This reverts commit 284350bab94e96d948164d98986d0fba7d1fa78f.
=> Revert "[front] maintenance error (#238)"

back/module/schoolcalendar/data/event_gen.json, back/module/schoolcalendar/data/module_detail_gen.json, codegen/schoolcalendar/README.md, codegen/schoolcalendar/event/2025.json, codegen/schoolcalendar/module_detail/2025.json, codegen/schoolcalendar/verify.py
close: #252
年度期間等の検証を簡易的に行う `verify.py` も作成しました
=> 2025年度学年暦カレンダーの作成

front/src/ui/pages/import.vue
close #267 
https://app.twinte.net/import?year=2025&codes= にアクセスした時にエラーとなっていたのを、以下の画面が表示されるように修正した。
=> [front] インポートする授業がない場合にクラッシュする問題を修正

back/handler/calendar/v1beta/calendar.go, back/handler/calendar/v1beta/handler.go, back/handler/calendar/v1beta/ics.go, back/handler/calendar/v1beta/impl.go, back/handler/calendar/v1beta/jst.go, back/handler/calendar/v1beta/period.go, back/handler/calendar/v1beta/school_calendar.go, back/handler/impl.go, proxy/nginx.docker.conf, proxy/nginx.host.conf
https://github.com/twin-te/calendar-service をv4に移植しました。
=> [back] calendar-serviceを移植

front/src/ui/pages/import-room/excel.vue
Excelのアップロードにかかった時間などを調査するためSentryのSpanをアップロード時に生成するようにしました。
参考: [Sending Span Metrics | Sentry for Vue](https://docs.sentry.io/platforms/javascript/guides/vue/tracing/span-metrics/)
以下の2点を確認してほしいです
- Sentryに正しくSpanがアップロードされるかどうか
- 計装以前とで挙動に変化がないかどうか
=> Excelアップロードの成功/失敗をSentryのトレーシングで追跡する

docker-compose.yml
fix #293 
手元ではmasterだと毎回動かなかったのがこの変更で動くようになったので動くと信じています
=> db のヘルスチェックを追加

front/src/ui/pages/settings.vue, front/src/ui/templates/Sidebar.vue
サイドバー上部にあったログアウトボタンを設定ページへと移動した. 
ログインボタンはサイドバー上部に残したまま
=> ログアウトボタンの移動

back/handler/calendar/v1beta/handler.go, back/handler/calendar/v1beta/ics.go
=> RDATE に対応しないクライアントのためのフォールバックを実装

sponsorship/next-seo.config.ts, sponsorship/pages/success.tsx
レビューで sponsorship.twinte.net へのリンクが残っていないかを確認してほしいです
=> [sponsorship] sponsorship.twinte.net -> app.twinte.net/sponsorship

back/module/announcement/data/announcement.json
=> [back] 利用者アンケートのお知らせを追加

.github/workflows/cd-production.yml, .github/workflows/cd-staging.yml
=> [infra] CDのSSH方法を変更

front/.dockerignore, front/Dockerfile, front/package.json
=> Revert "[front] oven/bunをベースイメージとして用いるように"

parser/download_and_parse.py, parser/pyproject.toml, parser/uv.lock
https://twin-te.sentry.io/issues/6772887165/?project=4509354103144448&query=&referrer=issue-stream
=> [parser] Sentryをparserに追加

front/src/ui/pages/login.vue
=> Revert "[front] 「Appleでログイン」のボタンを一時的に削除"

front/src/ui/pages/login.vue
=> Revert "Revert "[front] 「Appleでログイン」のボタンを一時的に削除""

front/src/ui/pages/login.vue
=> Revert "Revert "Revert "[front] 「Appleでログイン」のボタンを一時的に削除"""

front/.dockerignore, front/Dockerfile, front/package.json
=> Revert "Revert "[front] oven/bunをベースイメージとして用いるように""
